//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFK
    {
        public short IslemTip { get; set; }
        public string EvrakNo { get; set; }
        public int EvrakTarih { get; set; }
        public string HesapKod { get; set; }
        public short KynkEvrakTip { get; set; }
        public int Tarih { get; set; }
        public decimal Tutar { get; set; }
        public string Aciklama { get; set; }
        public string Aciklama2 { get; set; }
        public string Aciklama3 { get; set; }
        public string Aciklama4 { get; set; }
        public string Aciklama5 { get; set; }
        public string Aciklama6 { get; set; }
        public string Kod1 { get; set; }
        public string Kod2 { get; set; }
        public string Kod3 { get; set; }
        public string Kod4 { get; set; }
        public string Kod5 { get; set; }
        public decimal Kod6 { get; set; }
        public decimal Kod7 { get; set; }
        public string Nesne1 { get; set; }
        public string Nesne2 { get; set; }
        public string Nesne3 { get; set; }
        public int OnaySemaKod { get; set; }
        public short OnayIslemTip { get; set; }
        public short OnayStatus { get; set; }
        public string SonOnaylayan { get; set; }
        public string Onaylayan1 { get; set; }
        public string Onaylayan2 { get; set; }
        public string Onaylayacak { get; set; }
        public string GuvenlikKod { get; set; }
        public string Kaydeden { get; set; }
        public int KayitTarih { get; set; }
        public int KayitSaat { get; set; }
        public short KayitKaynak { get; set; }
        public string KayitSurum { get; set; }
        public string Degistiren { get; set; }
        public int DegisTarih { get; set; }
        public int DegisSaat { get; set; }
        public short DegisKaynak { get; set; }
        public string DegisSurum { get; set; }
        public short CheckSum { get; set; }
        public string Depo { get; set; }
        public string OnayTakipNo { get; set; }
        public int ROW_ID { get; set; }
        public byte[] timestamp { get; set; }
    }
}
