<?xml version="1.0" encoding="utf-8"?><Database Name="solar6" Class="TBKDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TESTSERVER;Initial Catalog=solar6;Persist Security Info=True;User ID=sa" SettingsObjectName="TakvimeBagliKisit.Properties.Settings" SettingsPropertyName="solar6ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBK" Member="TBKs" AccessModifier="Internal">
    <Type Name="TBK" AccessModifier="Internal">
      <Column Name="KullaniciKodu" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EvrakTipi" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SirketKodu" Type="System.String" DbType="VarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DonemKodu" Type="System.String" DbType="VarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DonemTipi" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DonemTarihi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KisitTipi" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Gun" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BasTarih" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BitTarih" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Row_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="timestamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
    </Type>
  </Table>
</Database>