//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppLog
    {
        public int ID { get; set; }
        public string Site { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public int Type { get; set; }
        public Nullable<int> SelectedID { get; set; }
        public string Details { get; set; }
        public string Request { get; set; }
        public string Username { get; set; }
        public string IpAddress { get; set; }
        public System.DateTime Tarih { get; set; }
    }
}
