//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR005
    {
        public int CAR005_Row_ID { get; set; }
        public Nullable<short> CAR005_Secenek { get; set; }
        public Nullable<int> CAR005_FaturaTarihi { get; set; }
        public string CAR005_FaturaNo { get; set; }
        public string CAR005_BA { get; set; }
        public Nullable<short> CAR005_CariIslemTipi { get; set; }
        public string CAR005_SatirTipi { get; set; }
        public Nullable<short> CAR005_SatirNo { get; set; }
        public string CAR005_SatirKodu { get; set; }
        public string CAR005_Filler { get; set; }
        public string CAR005_SatirAciklama { get; set; }
        public string CAR005_CHKodu { get; set; }
        public Nullable<decimal> CAR005_Tutar { get; set; }
        public Nullable<decimal> CAR005_Oran { get; set; }
        public Nullable<int> CAR005_TevkIslemTuru { get; set; }
        public string CAR005_TevkOrani { get; set; }
        public Nullable<decimal> CAR005_TevkKDVOrani { get; set; }
        public string CAR005_EkBilgi1 { get; set; }
        public string CAR005_EFaturaOTVListeNo { get; set; }
        public Nullable<byte> CAR005_EFaturaTipi { get; set; }
        public Nullable<short> CAR005_EFaturaDurumu { get; set; }
        public Nullable<int> CAR005_EFaturaDonemBas { get; set; }
        public Nullable<int> CAR005_EFaturaDonemBit { get; set; }
        public Nullable<int> CAR005_EFaturaSure { get; set; }
        public Nullable<byte> CAR005_EFaturaSureBirimi { get; set; }
        public string CAR005_EFaturaDonemAciklama { get; set; }
        public string CAR005_EFaturaNot { get; set; }
        public string CAR005_EFaturaReferansNo { get; set; }
        public Nullable<byte> CAR005_ParaBirimi { get; set; }
        public string CAR005_DovizCinsi { get; set; }
        public Nullable<decimal> CAR005_DovizKuru { get; set; }
        public Nullable<decimal> CAR005_DovizTutari { get; set; }
        public string CAR005_TeslimCHKodu { get; set; }
        public Nullable<byte> CAR005_TutarAlanDegeri { get; set; }
        public string CAR005_KDVMuafAciklama { get; set; }
        public string CAR005_EFaturaGonBirimEtiketi { get; set; }
        public string CAR005_EFaturaAliciEtiketi { get; set; }
        public string CAR005_AliciSiparisNo { get; set; }
        public Nullable<int> CAR005_AliciSiparisTarihi { get; set; }
        public Nullable<byte> CAR005_IptalDurumu { get; set; }
        public Nullable<byte> CAR005_EArsivFaturaTipi { get; set; }
        public Nullable<byte> CAR005_EArsivFaturaTeslimSekli { get; set; }
        public Nullable<short> CAR005_EArsivFaturaDurumu { get; set; }
    }
}
