//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR036
    {
        public int CAR036_Row_ID { get; set; }
        public Nullable<int> CAR036_Ulke { get; set; }
        public string CAR036_VergiHesapNo { get; set; }
        public string CAR036_CHUnvani { get; set; }
        public Nullable<int> CAR036_EvrakSayisi { get; set; }
        public Nullable<decimal> CAR036_Tutar { get; set; }
        public string CAR036_HesapKodu { get; set; }
        public Nullable<byte> CAR036_FormBUnvanFlag { get; set; }
    }
}
