//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR003
    {
        public int CAR003_Row_ID { get; set; }
        public string CAR003_HesapKodu { get; set; }
        public Nullable<int> CAR003_Tarih { get; set; }
        public Nullable<short> CAR003_IslemTipi { get; set; }
        public string CAR003_EvrakSeriNo { get; set; }
        public string CAR003_Aciklama { get; set; }
        public Nullable<byte> CAR003_BA { get; set; }
        public Nullable<decimal> CAR003_Tutar { get; set; }
        public Nullable<int> CAR003_VadeTarihi { get; set; }
        public string CAR003_KarsiEvrakSeriNo { get; set; }
        public string CAR003_Kod1 { get; set; }
        public string CAR003_Kod2 { get; set; }
        public Nullable<byte> CAR003_KDVOrani { get; set; }
        public Nullable<byte> CAR003_KDVDahilHaric { get; set; }
        public Nullable<byte> CAR003_MuhasebelesmeDurumu { get; set; }
        public Nullable<byte> CAR003_ParaBirimi { get; set; }
        public Nullable<int> CAR003_SEQNo { get; set; }
        public string CAR003_GirenKaynak { get; set; }
        public Nullable<int> CAR003_GirenTarih { get; set; }
        public string CAR003_GirenSaat { get; set; }
        public string CAR003_GirenKodu { get; set; }
        public string CAR003_GirenSurum { get; set; }
        public string CAR003_DegistirenKaynak { get; set; }
        public Nullable<int> CAR003_DegistirenTarih { get; set; }
        public string CAR003_DegistirenSaat { get; set; }
        public string CAR003_DegistirenKodu { get; set; }
        public string CAR003_DegistirenSurum { get; set; }
        public Nullable<byte> CAR003_IptalDurumu { get; set; }
        public Nullable<int> CAR003_AsilEvrakTarihi { get; set; }
        public Nullable<byte> CAR003_otvdahilharic { get; set; }
        public Nullable<decimal> CAR003_otvtutari { get; set; }
        public string CAR003_KarsiHesapKodu { get; set; }
        public string CAR003_Kod3 { get; set; }
        public string CAR003_Kod4 { get; set; }
        public string CAR003_Kod5 { get; set; }
        public string CAR003_Kod6 { get; set; }
        public string CAR003_Kod7 { get; set; }
        public string CAR003_Kod8 { get; set; }
        public string CAR003_Kod9 { get; set; }
        public string CAR003_Kod10 { get; set; }
        public Nullable<decimal> CAR003_Kod11 { get; set; }
        public Nullable<decimal> CAR003_Kod12 { get; set; }
        public Nullable<decimal> CAR003_Tutar2 { get; set; }
        public Nullable<int> CAR003_Tarih2 { get; set; }
        public string CAR003_Aciklama2 { get; set; }
        public string CAR003_EvrakSeriNo2 { get; set; }
        public string CAR003_DovizCinsi { get; set; }
        public Nullable<decimal> CAR003_DovizTutari { get; set; }
        public Nullable<decimal> CAR003_DovizKuru { get; set; }
        public string CAR003_SenetCekBordroNo { get; set; }
        public Nullable<short> CAR003_SenetCekPozisyonTipi { get; set; }
        public Nullable<short> CAR003_MuhasebelesmeSekli { get; set; }
        public Nullable<int> CAR003_MuhasebeFisTarihi { get; set; }
        public Nullable<byte> CAR003_MuhasebeTipi { get; set; }
        public Nullable<int> CAR003_MuhasebeFisNumarasi { get; set; }
        public string CAR003_MuhasebeFisKodu { get; set; }
        public Nullable<short> CAR003_MuhasebeSiraNo { get; set; }
        public string CAR003_MuhasebeHesapNo { get; set; }
        public string CAR003_MuhasebeKarsiHeaspNo { get; set; }
        public Nullable<byte> CAR003_MuhasebeYevmiyeSekli { get; set; }
        public string CAR003_IskontoTuru { get; set; }
        public string CAR003_EvrakSeriNo3 { get; set; }
        public string CAR003_MasrafMerkezi { get; set; }
        public Nullable<int> CAR003_VadeFarkiTarihi { get; set; }
        public Nullable<decimal> CAR003_VadeFarkiTutari { get; set; }
        public Nullable<decimal> CAR003_FaizOrani { get; set; }
        public Nullable<int> CAR003_Ulke { get; set; }
        public string CAR003_VergiHesapNo { get; set; }
        public string CAR003_Unvani { get; set; }
        public Nullable<short> CAR003_EvrakSayisi { get; set; }
        public Nullable<short> CAR003_EvrakTipi { get; set; }
        public Nullable<int> CAR003_MHSMaddeNo { get; set; }
        public string CAR003_IBAN { get; set; }
        public Nullable<int> CAR003_KKPOSTableRowID { get; set; }
        public Nullable<short> CAR003_KKTaksitSayisi { get; set; }
        public Nullable<short> CAR003_KKTaksitNo { get; set; }
        public Nullable<int> CAR003_KKKomisyonID { get; set; }
        public Nullable<int> CAR003_KDVTevkIslemTuru { get; set; }
        public string CAR003_KDVTevkOrani { get; set; }
        public string CAR003_IthalatNo { get; set; }
        public Nullable<byte> CAR003_IthalatAktarmaFlag { get; set; }
        public Nullable<decimal> CAR003_KDVTevkIslemBedeli { get; set; }
        public string CAR003_OdemeTipi { get; set; }
        public Nullable<byte> CAR003_YevmiyeEvrakTip { get; set; }
        public string CAR003_EvrakTipAciklama { get; set; }
        public Nullable<byte> CAR003_EFaturaTipi { get; set; }
        public Nullable<short> CAR003_EFaturaDurumu { get; set; }
        public string CAR003_EFaturaOTVListeNo { get; set; }
        public Nullable<int> CAR003_EFaturaDonemBas { get; set; }
        public Nullable<int> CAR003_EFaturaDonemBit { get; set; }
        public Nullable<int> CAR003_EFaturaSure { get; set; }
        public Nullable<byte> CAR003_EFaturaSureBirimi { get; set; }
        public string CAR003_EFaturaDonemAciklama { get; set; }
        public string CAR003_EFaturaNot { get; set; }
        public string CAR003_EFaturaReferansNo { get; set; }
        public string CAR003_YevEvrakNo { get; set; }
        public Nullable<int> CAR003_YevEvrakTarihi { get; set; }
        public Nullable<decimal> CAR003_StopajOrani { get; set; }
        public Nullable<short> CAR003_OdemeTuru { get; set; }
        public string CAR003_TalimatNo { get; set; }
        public string CAR003_IhracatNo { get; set; }
        public Nullable<int> CAR003_GrpSiraNo { get; set; }
        public Nullable<byte> CAR003_EArsivFaturaTipi { get; set; }
        public Nullable<byte> CAR003_EArsivFaturaTeslimSekli { get; set; }
        public Nullable<short> CAR003_EArsivFaturaDurumu { get; set; }
        public string CAR003_EArsivAdres { get; set; }
        public string CAR003_EArsivSemt { get; set; }
        public string CAR003_EArsivIL { get; set; }
        public string CAR003_Unvani2 { get; set; }
        public string CAR003_YOKCSeriNo { get; set; }
        public Nullable<int> CAR003_YOKCZRaporuNo { get; set; }
        public Nullable<byte> CAR003_YOKCBelgeTipi { get; set; }
        public Nullable<byte> CAR003_YOKCBilgiFisiTipi { get; set; }
        public Nullable<int> CAR003_YOKCFisNo { get; set; }
        public Nullable<int> CAR003_YOKCFisTarihi { get; set; }
        public string CAR003_OdemeTurKodu { get; set; }
        public Nullable<int> CAR003_VergiDairesiKodu { get; set; }
        public Nullable<int> CAR003_FiiliIhracatTarihi { get; set; }
        public string CAR003_YOKCFisSaat { get; set; }
        public Nullable<byte> CAR003_YOKCDuzenlemeTip { get; set; }
        public string CAR003_YOKCBankaOnayKod { get; set; }
        public string CAR003_YOKCUniqueID { get; set; }
    }
}
