//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR124
    {
        public int CAR124_Row_ID { get; set; }
        public Nullable<byte> CAR124_DosyaTipi { get; set; }
        public string CAR124_DosyaNo { get; set; }
        public string CAR124_DosyaAdi { get; set; }
        public string CAR124_HesapKodu { get; set; }
        public string CAR124_GumrukKod { get; set; }
        public Nullable<int> CAR124_TescilTarihi { get; set; }
        public string CAR124_TescilNo { get; set; }
        public Nullable<int> CAR124_FiiliTarih { get; set; }
        public string CAR124_DovizCinsi { get; set; }
        public Nullable<decimal> CAR124_DovizKuru { get; set; }
        public Nullable<decimal> CAR124_MalBedeli { get; set; }
        public Nullable<decimal> CAR124_GumrukVergisi { get; set; }
        public Nullable<decimal> CAR124_TopOTVTutar { get; set; }
        public Nullable<decimal> CAR124_TopKDVTutar { get; set; }
        public Nullable<decimal> CAR124_DamgaVergisi { get; set; }
        public string CAR124_BankaHesapKodu { get; set; }
        public Nullable<int> CAR124_BankaKodu { get; set; }
        public string CAR124_BankaSubeKodu { get; set; }
        public string CAR124_IBAN { get; set; }
        public string CAR124_HesapNo { get; set; }
        public string CAR124_EkliDosyaDizin { get; set; }
        public Nullable<decimal> CAR124_MalBedeliDvz { get; set; }
        public string CAR124_GirenKaynak { get; set; }
        public Nullable<int> CAR124_GirenTarih { get; set; }
        public string CAR124_GirenSaat { get; set; }
        public string CAR124_GirenKodu { get; set; }
        public string CAR124_GirenSurum { get; set; }
        public string CAR124_DegistirenKaynak { get; set; }
        public Nullable<int> CAR124_DegistirenTarih { get; set; }
        public string CAR124_DegistirenSaat { get; set; }
        public string CAR124_DegistirenKodu { get; set; }
        public string CAR124_DegistirenSurum { get; set; }
    }
}
