//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR151
    {
        public int CAR151_Row_ID { get; set; }
        public string CAR151_PosKodu { get; set; }
        public string CAR151_PosAdi { get; set; }
        public Nullable<int> CAR151_BankaKodu { get; set; }
        public string CAR151_KartTipi { get; set; }
        public string CAR151_GirenKaynak { get; set; }
        public Nullable<int> CAR151_GirenTarih { get; set; }
        public string CAR151_GirenSaat { get; set; }
        public string CAR151_GirenKodu { get; set; }
        public string CAR151_GirenSurum { get; set; }
        public string CAR151_DegistirenKaynak { get; set; }
        public Nullable<int> CAR151_DegistirenTarih { get; set; }
        public string CAR151_DegistirenSaat { get; set; }
        public string CAR151_DegistirenKodu { get; set; }
        public string CAR151_DegistirenSurum { get; set; }
    }
}
