//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR123
    {
        public int CAR123_Row_ID { get; set; }
        public string CAR123_HesapKodu { get; set; }
        public Nullable<int> CAR123_SiraNo { get; set; }
        public string CAR123_RefTip { get; set; }
        public string CAR123_DocTip { get; set; }
        public string CAR123_DocIDTablo { get; set; }
        public string CAR123_DocID { get; set; }
        public string CAR123_DocTarihTablo { get; set; }
        public string CAR123_DocTarih { get; set; }
        public string CAR123_NotTablo { get; set; }
        public string CAR123_Not { get; set; }
    }
}
