//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR204
    {
        public int CAR204_Row_ID { get; set; }
        public string CAR204_EVTUserCode { get; set; }
        public string CAR204_EVTTakenDocFolder { get; set; }
        public string CAR204_EVTSaveDocFolder { get; set; }
        public Nullable<int> CAR204_EVTNoOrgCodeInTakenDoc { get; set; }
        public Nullable<int> CAR204_EVTCHCantFind { get; set; }
        public Nullable<int> CAR204_EVTReturnInvRelatedInv { get; set; }
        public Nullable<int> CAR204_EVTDocObjectCode { get; set; }
        public Nullable<int> CAR204_EVTCantFindObjCode { get; set; }
        public Nullable<int> CAR204_EVTReturnDetRelatedDet { get; set; }
        public string CAR204_EVTNewCardTransFields { get; set; }
        public string CAR204_EVTTransDetailFields { get; set; }
    }
}
