//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR205
    {
        public int CAR205_Row_ID { get; set; }
        public string CAR205_GUName { get; set; }
        public Nullable<short> CAR205_FATFaturaSatisSInd { get; set; }
        public Nullable<short> CAR205_FATIrsaliyeSatisSInd { get; set; }
        public Nullable<short> CAR205_FATSiparisSatisSInd { get; set; }
        public Nullable<short> CAR205_FATOKCSInd { get; set; }
        public Nullable<short> CAR205_FATFaturaAlimSInd { get; set; }
        public Nullable<short> CAR205_FATIrsaliyeAlimSInd { get; set; }
        public Nullable<short> CAR205_FATSiparisAlimSInd { get; set; }
        public Nullable<short> CAR205_FATMustahsilMakSInd { get; set; }
        public Nullable<short> CAR205_FATSerbMeslekMakSInd { get; set; }
    }
}
