//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR210
    {
        public int CAR210_Row_ID { get; set; }
        public string CAR210_HesapKodu { get; set; }
        public Nullable<int> CAR210_Tarih { get; set; }
        public string CAR210_EvrakSeriNo { get; set; }
        public Nullable<short> CAR210_IslemTipi { get; set; }
        public Nullable<byte> CAR210_BA { get; set; }
        public Nullable<short> CAR210_EvrakTipi { get; set; }
        public Nullable<decimal> CAR210_Tutar { get; set; }
    }
}
