//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR211
    {
        public int CAR211_Row_ID { get; set; }
        public string CAR211_HesapKodu { get; set; }
        public Nullable<int> CAR211_FaturaTarihi { get; set; }
        public string CAR211_FaturaNo { get; set; }
        public string CAR211_FaturaReferansNo { get; set; }
        public string CAR211_Ad { get; set; }
        public string CAR211_Soyad { get; set; }
        public string CAR211_Adres { get; set; }
        public string CAR211_Semt { get; set; }
        public string CAR211_Sehir { get; set; }
        public Nullable<int> CAR211_Ulke { get; set; }
        public string CAR211_Uyruk { get; set; }
        public string CAR211_PasaportNo { get; set; }
        public Nullable<int> CAR211_PasaportGecerTarih { get; set; }
        public string CAR211_DovizCinsi { get; set; }
        public string CAR211_Banka { get; set; }
        public string CAR211_BankaSube { get; set; }
        public string CAR211_BankaHesapNo { get; set; }
        public string CAR211_OdemeNotu { get; set; }
        public string CAR211_KrediKartiNo { get; set; }
        public string CAR211_KrediKartiTipi { get; set; }
    }
}
