//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Aylik_SatisAnalizi
    {
        public int ID { get; set; }
        public string DB { get; set; }
        public string Ay { get; set; }
        public decimal Yil2015 { get; set; }
        public decimal Yil2016 { get; set; }
        public decimal Yil2017 { get; set; }
    }
}
