//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEP
    {
        public string Depo { get; set; }
        public string DepoAdi { get; set; }
        public string Adres1 { get; set; }
        public string Adres2 { get; set; }
        public string Adres3 { get; set; }
        public string Telefon1 { get; set; }
        public string Telefon2 { get; set; }
        public string Telefon3 { get; set; }
        public string Fax { get; set; }
        public string BolgeKod { get; set; }
        public string GrupKod { get; set; }
        public string TipKod { get; set; }
        public string Kod1 { get; set; }
        public string Kod2 { get; set; }
        public string Kod3 { get; set; }
        public string Yetkili1 { get; set; }
        public string Yetkili2 { get; set; }
        public string Yetkili1EMail { get; set; }
        public string Yetkili2EMail { get; set; }
        public decimal SonSayimSonuc { get; set; }
        public short MerkezDepo { get; set; }
        public string GuvenlikKod { get; set; }
        public string Kaydeden { get; set; }
        public int KayitTarih { get; set; }
        public int KayitSaat { get; set; }
        public short KayitKaynak { get; set; }
        public string KayitSurum { get; set; }
        public string Degistiren { get; set; }
        public int DegisTarih { get; set; }
        public int DegisSaat { get; set; }
        public short DegisKaynak { get; set; }
        public string DegisSurum { get; set; }
        public short CheckSum { get; set; }
        public string GirisMhsKod { get; set; }
        public string CikisMhsKod { get; set; }
        public string TuketimMhsKod { get; set; }
        public short DepoTipi { get; set; }
        public int ROW_ID { get; set; }
        public byte[] timestamp { get; set; }
    }
}
