//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DST
    {
        public string MalKodu { get; set; }
        public string Depo { get; set; }
        public decimal KritikStok { get; set; }
        public decimal AzamiStok { get; set; }
        public decimal DvrMiktar { get; set; }
        public decimal DvrTutar { get; set; }
        public int DvrTarih { get; set; }
        public decimal GirMiktar { get; set; }
        public decimal GirTutar { get; set; }
        public decimal GirIskonto { get; set; }
        public decimal DvzGirTutar { get; set; }
        public decimal DvzGirIskonto { get; set; }
        public int SonGirTarih { get; set; }
        public decimal CikMiktar { get; set; }
        public decimal CikTutar { get; set; }
        public decimal CikIskonto { get; set; }
        public decimal DvzCikTutar { get; set; }
        public decimal DvzCikIskonto { get; set; }
        public int SonCikTarih { get; set; }
        public int SonSayimTarih { get; set; }
        public decimal SonSayimFarki { get; set; }
        public decimal SatSiparis { get; set; }
        public decimal AlSiparis { get; set; }
        public decimal SatRezervasyon { get; set; }
        public decimal AlRezervasyon { get; set; }
        public decimal KonsGirMiktar { get; set; }
        public decimal KonsCikMiktar { get; set; }
        public short SonMlySekli { get; set; }
        public int SonMlyTarih { get; set; }
        public decimal SonMlyBirimFiyat { get; set; }
        public decimal Miktar2 { get; set; }
        public decimal Tutar2 { get; set; }
        public decimal BlkMiktar { get; set; }
        public string Kod1 { get; set; }
        public string Kod2 { get; set; }
        public string Kod3 { get; set; }
        public string Kod4 { get; set; }
        public decimal Kod5 { get; set; }
        public decimal Kod6 { get; set; }
        public string Kod7 { get; set; }
        public string Kod8 { get; set; }
        public string Kod9 { get; set; }
        public short Kod10 { get; set; }
        public short Kod11 { get; set; }
        public decimal Kod12 { get; set; }
        public decimal Kod13 { get; set; }
        public short BakGostSekli { get; set; }
        public string GuvenlikKod { get; set; }
        public string Kaydeden { get; set; }
        public int KayitTarih { get; set; }
        public int KayitSaat { get; set; }
        public short KayitKaynak { get; set; }
        public string KayitSurum { get; set; }
        public string Degistiren { get; set; }
        public int DegisTarih { get; set; }
        public int DegisSaat { get; set; }
        public short DegisKaynak { get; set; }
        public string DegisSurum { get; set; }
        public short CheckSum { get; set; }
        public decimal TahminiStok { get; set; }
        public int ROW_ID { get; set; }
        public byte[] timestamp { get; set; }
    }
}
