//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVZ002
    {
        public int DVZ002_Row_ID { get; set; }
        public Nullable<int> DVZ002_DovizDate { get; set; }
        public Nullable<short> DVZ002_DvzBanka { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis1 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis1 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis1 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis1 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis2 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis2 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis2 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis2 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis3 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis3 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis3 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis3 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis4 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis4 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis4 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis4 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis5 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis5 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis5 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis5 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis6 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis6 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis6 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis6 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis7 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis7 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis7 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis7 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis8 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis8 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis8 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis8 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis9 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis9 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis9 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis9 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis10 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis10 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis10 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis10 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis11 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis11 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis11 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis11 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis12 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis12 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis12 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis12 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis13 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis13 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis13 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis13 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis14 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis14 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis14 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis14 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis15 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis15 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis15 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis15 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis16 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis16 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis16 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis16 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis17 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis17 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis17 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis17 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis18 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis18 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis18 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis18 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis19 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis19 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis19 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis19 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis20 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis20 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis20 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis20 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis21 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis21 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis21 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis21 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis22 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis22 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis22 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis22 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis23 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis23 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis23 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis23 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis24 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis24 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis24 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis24 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis25 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis25 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis25 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis25 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis26 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis26 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis26 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis26 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis27 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis27 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis27 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis27 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis28 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis28 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis28 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis28 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis29 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis29 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis29 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis29 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis30 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis30 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis30 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis30 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis31 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis31 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis31 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis31 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis32 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis32 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis32 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis32 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis33 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis33 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis33 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis33 { get; set; }
        public Nullable<decimal> DVZ002_DvzAlis34 { get; set; }
        public Nullable<decimal> DVZ002_DvzSatis34 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektifAlis34 { get; set; }
        public Nullable<decimal> DVZ002_DvzEfektisSatis34 { get; set; }
        public string DVZ002_DvzGirKayNo { get; set; }
        public Nullable<int> DVZ002_DvzGirDate { get; set; }
        public string DVZ002_DvzGirTime { get; set; }
        public string DVZ002_DvzGirKodu { get; set; }
        public string DVZ002_DvzGirsVers { get; set; }
        public string DVZ002_DvzDegKayNo { get; set; }
        public Nullable<int> DVZ002_DvzDegDate { get; set; }
        public string DVZ002_DvzDegTime { get; set; }
        public string DVZ002_DvzDegKodu { get; set; }
        public string DVZ002_DvzDegVers { get; set; }
    }
}
