//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTD
    {
        public short IslemTip { get; set; }
        public short BA { get; set; }
        public string EvrakNo { get; set; }
        public int Tarih { get; set; }
        public string HesapKodu { get; set; }
        public short SiraNo { get; set; }
        public short SatirTip { get; set; }
        public string Aciklama { get; set; }
        public string IskontoTur { get; set; }
        public float IskontoOran { get; set; }
        public decimal Iskonto { get; set; }
        public short DvzTL { get; set; }
        public string DovizCinsi { get; set; }
        public decimal DovizTutar { get; set; }
        public decimal DovizKuru { get; set; }
        public short Printed { get; set; }
        public string FytListeNo { get; set; }
        public string TeslimChk { get; set; }
        public short NakliYekun { get; set; }
        public short DvzKurCins { get; set; }
        public string GuvenlikKod { get; set; }
        public string Kaydeden { get; set; }
        public int KayitTarih { get; set; }
        public int KayitSaat { get; set; }
        public short KayitKaynak { get; set; }
        public string KayitSurum { get; set; }
        public string Degistiren { get; set; }
        public int DegisTarih { get; set; }
        public int DegisSaat { get; set; }
        public short DegisKaynak { get; set; }
        public string DegisSurum { get; set; }
        public short CheckSum { get; set; }
        public short KynkEvrakTip { get; set; }
        public short AnaEvrakTip { get; set; }
        public int FormBaBsTarih { get; set; }
        public string IthalatDosyaNo { get; set; }
        public string TevkifatOran { get; set; }
        public short EFatTip { get; set; }
        public short EFatDurum { get; set; }
        public int EFatDonemBas { get; set; }
        public int EFatDonemBit { get; set; }
        public short EFatSure { get; set; }
        public short EFatSureDurum { get; set; }
        public string EFatDonemAck { get; set; }
        public string EFatNot { get; set; }
        public string EFatReferansNo { get; set; }
        public string GtkListeNo { get; set; }
        public decimal YuvFark { get; set; }
        public decimal DvzYuvFark { get; set; }
        public string KDVMuafAck { get; set; }
        public string EfatEtiketGB { get; set; }
        public string EfatEtiketPK { get; set; }
        public string AliciSiparisNo { get; set; }
        public int AliciSiparisTarih { get; set; }
        public string IhracatDosyaNo { get; set; }
        public string TevkifatOranKod { get; set; }
        public string OzelMatKDVKod { get; set; }
        public short EArsivTeslimSekli { get; set; }
        public short EArsivFaturaTipi { get; set; }
        public short EArsivFaturaDurum { get; set; }
        public int FaturaSaati { get; set; }
        public int ROW_ID { get; set; }
        public byte[] timestamp { get; set; }
    }
}
