//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN14SCS
    {
        public int GENId { get; set; }
        public string GENAltId { get; set; }
        public short TableId { get; set; }
        public string FieldName { get; set; }
        public string FieldValue { get; set; }
    }
}
