//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GorevPaketler
    {
        public int GorevID { get; set; }
        public string SevkiyatNo { get; set; }
        public string PaketNo { get; set; }
        public decimal Adet { get; set; }
        public int PaketTipiID { get; set; }
        public decimal Agirlik { get; set; }
        public bool Printed { get; set; }
        public string Kaydeden { get; set; }
        public int KayitTarih { get; set; }
        public string Degistiren { get; set; }
        public int DegisTarih { get; set; }
    
        public virtual ComboItem_Name ComboItem_Name { get; set; }
        public virtual Gorev Gorev { get; set; }
    }
}
