//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GorevNo
    {
        public int Tarih { get; set; }
        public int DepoID { get; set; }
        public int No { get; set; }
    
        public virtual Depo Depo { get; set; }
    }
}
