//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IRS_Detay
    {
        public int ID { get; set; }
        public int IrsaliyeID { get; set; }
        public string MalKodu { get; set; }
        public decimal Miktar { get; set; }
        public string Birim { get; set; }
        public Nullable<int> KynkSiparisID { get; set; }
        public string KynkSiparisNo { get; set; }
        public Nullable<short> KynkSiparisSiraNo { get; set; }
        public Nullable<int> KynkSiparisTarih { get; set; }
        public Nullable<decimal> KynkSiparisMiktar { get; set; }
        public Nullable<decimal> OkutulanMiktar { get; set; }
        public Nullable<decimal> YerlestirmeMiktari { get; set; }
        public Nullable<int> KynkDegisSaat { get; set; }
    
        public virtual IR IR { get; set; }
    }
}
