//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISL006
    {
        public int ISL006_Row_ID { get; set; }
        public Nullable<int> ISL006_ReferansTuru { get; set; }
        public string ISL006_ReferansKodu { get; set; }
        public string ISL006_ReferansAciklamasi { get; set; }
        public string ISL006_ReferansGrupKodu { get; set; }
        public Nullable<decimal> ISL006_ReferansKod1 { get; set; }
    }
}
