//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kat()
        {
            this.Yers = new HashSet<Yer>();
            this.Yer_Log = new HashSet<Yer_Log>();
        }
    
        public int ID { get; set; }
        public int BolumID { get; set; }
        public string KatAd { get; set; }
        public decimal Boy { get; set; }
        public decimal Derinlik { get; set; }
        public decimal En { get; set; }
        public decimal AgirlikKapasite { get; set; }
        public int Ozellik { get; set; }
        public string Aciklama { get; set; }
        public int SiraNo { get; set; }
        public bool Aktif { get; set; }
        public int Kaydeden { get; set; }
        public int KayitTarih { get; set; }
        public int Degistiren { get; set; }
        public int DegisTarih { get; set; }
    
        public virtual ComboItem_Name ComboItem_Name { get; set; }
        public virtual Bolum Bolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yer> Yers { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yer_Log> Yer_Log { get; set; }
    }
}
