//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public bool LoggedIn { get; set; }
        public string Comment { get; set; }
    }
}
