//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MBO006
    {
        public int MBO006_Row_ID { get; set; }
        public Nullable<int> MBO006_ReferansTuru { get; set; }
        public string MBO006_ReferansKodu { get; set; }
        public string MBO006_ReferansAciklamasi { get; set; }
        public string MBO006_ReferansGrupKodu { get; set; }
        public Nullable<decimal> MBO006_ReferansKod1 { get; set; }
    }
}
