//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int ID { get; set; }
        public int FromID { get; set; }
        public Nullable<int> ToID { get; set; }
        public string Message1 { get; set; }
        public bool Okundu { get; set; }
        public bool GonderenSildi { get; set; }
        public bool AliciSildi { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
