//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHS010
    {
        public int MHS010_Row_ID { get; set; }
        public Nullable<int> MHS010_TKIslemTarihi { get; set; }
        public Nullable<byte> MHS010_TKFisTipi { get; set; }
        public Nullable<int> MHS010_TKFisNo { get; set; }
        public string MHS010_TKFisKodu { get; set; }
        public string MHS010_Aciklama1 { get; set; }
        public string MHS010_Aciklama2 { get; set; }
        public string MHS010_Aciklama3 { get; set; }
        public string MHS010_Aciklama4 { get; set; }
        public string MHS010_Aciklama5 { get; set; }
        public string MHS010_Aciklama6 { get; set; }
        public string MHS010_Aciklama7 { get; set; }
        public string MHS010_Aciklama8 { get; set; }
        public string MHS010_Aciklama9 { get; set; }
        public string MHS010_Aciklama10 { get; set; }
        public Nullable<int> MHS010_MaddeNo { get; set; }
        public string MHS010_GirenKaynak { get; set; }
        public Nullable<int> MHS010_GirenTarih { get; set; }
        public string MHS010_GirenSaat { get; set; }
        public string MHS010_GirenKodu { get; set; }
        public string MHS010_GirenSurum { get; set; }
        public string MHS010_DegistirenKaynak { get; set; }
        public Nullable<int> MHS010_DegistirenTarih { get; set; }
        public string MHS010_DegistirenSaat { get; set; }
        public string MHS010_DegistirenKodu { get; set; }
        public string MHS010_DegistirenSurum { get; set; }
    }
}
