//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHS006
    {
        public int MHS006_Row_ID { get; set; }
        public Nullable<int> MHS006_ReferansTuru { get; set; }
        public string MHS006_ReferansKodu { get; set; }
        public string MHS006_ReferansAciklamasi { get; set; }
        public string MHS006_ReferansGrupKodu { get; set; }
        public Nullable<decimal> MHS006_ReferansKod1 { get; set; }
    }
}
