//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHS005
    {
        public int MHS005_Row_ID { get; set; }
        public string MHS005_AltHesapKodu { get; set; }
        public Nullable<decimal> MHS005_DonemselDevirBorc { get; set; }
        public Nullable<decimal> MHS005_DonemselDevirAlacak { get; set; }
        public Nullable<decimal> MHS005_AcilisBorc { get; set; }
        public Nullable<decimal> MHS005_AcilisAlacak { get; set; }
        public Nullable<decimal> MHS005_KapanisBorc { get; set; }
        public Nullable<decimal> MHS005_KapanisAlacak { get; set; }
        public string MHS005_GirenKaynak { get; set; }
        public Nullable<int> MHS005_GirenTarih { get; set; }
        public string MHS005_GirenSaat { get; set; }
        public string MHS005_GirenKodu { get; set; }
        public string MHS005_GirenSurum { get; set; }
        public string MHS005_DegistirenKaynak { get; set; }
        public Nullable<int> MHS005_DegistirenTarih { get; set; }
        public string MHS005_DegistirenSaat { get; set; }
        public string MHS005_DegistirenKodu { get; set; }
        public string MHS005_DegistirenSurum { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc1 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak1 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc2 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak2 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc3 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak3 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc4 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak4 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc5 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak5 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc6 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak6 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc7 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak7 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc8 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak8 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc9 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak9 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc10 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak10 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc11 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak11 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc12 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak12 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc13 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak13 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc14 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak14 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc15 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak15 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc16 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak16 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc17 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak17 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc18 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak18 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc19 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak19 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc20 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak20 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc21 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak21 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc22 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak22 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc23 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak23 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikBorc24 { get; set; }
        public Nullable<decimal> MHS005_AylikBorcAlacakAylikAlacak24 { get; set; }
    }
}
