//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHS156
    {
        public int MHS156_Row_ID { get; set; }
        public Nullable<int> MHS156_Ulke { get; set; }
        public string MHS156_VergiHesapNo { get; set; }
        public string MHS156_CHUnvani { get; set; }
        public Nullable<int> MHS156_EvrakSayisi { get; set; }
        public Nullable<decimal> MHS156_Tutar { get; set; }
        public string MHS156_HesapKodu { get; set; }
        public Nullable<byte> MHS156_FormBUnvanFlag { get; set; }
    }
}
