//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHS171
    {
        public int MHS171_Row_ID { get; set; }
        public string MHS171_MhsEnfAltHesap { get; set; }
        public Nullable<int> MHS171_MhsEnfYil { get; set; }
        public Nullable<byte> MHS171_MhsEnfDonem { get; set; }
        public string MHS171_MhsEnfHisseSndKodu { get; set; }
        public Nullable<decimal> MHS171_MhsEnfMiktarLot { get; set; }
        public Nullable<decimal> MHS171_MhsEnfAlisBrmFiyat { get; set; }
        public Nullable<decimal> MHS171_MhsEnfBilAlisBrmFiyat { get; set; }
        public string MHS171_GirenKaynak { get; set; }
        public Nullable<int> MHS171_GirenTarih { get; set; }
        public string MHS171_GirenSaat { get; set; }
        public string MHS171_GirenKodu { get; set; }
        public string MHS171_GirenSurum { get; set; }
        public string MHS171_DegistirenKaynak { get; set; }
        public Nullable<int> MHS171_DegistirenTarih { get; set; }
        public string MHS171_DegistirenSaat { get; set; }
        public string MHS171_DegistirenKodu { get; set; }
        public string MHS171_DegistirenSurum { get; set; }
    }
}
