//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHS181
    {
        public int MHS181_Row_ID { get; set; }
        public Nullable<int> MHS181_MhsEnfYil { get; set; }
        public Nullable<byte> MHS181_MhsEnfDonem { get; set; }
        public string MHS181_MhsEnfAltHesap { get; set; }
        public string MHS181_MhsEnfFarkHesap { get; set; }
        public Nullable<decimal> MHS181_MhsEnfTarihiDeger { get; set; }
        public Nullable<decimal> MHS181_MhsEnfReelOlmFinMal { get; set; }
        public Nullable<decimal> MHS181_MhsEnfReelDeger { get; set; }
        public Nullable<decimal> MHS181_MhsEnfDuzeltDeger { get; set; }
        public Nullable<byte> MHS181_MhsEnfBA { get; set; }
        public string MHS181_GirenKaynak { get; set; }
        public Nullable<int> MHS181_GirenTarih { get; set; }
        public string MHS181_GirenSaat { get; set; }
        public string MHS181_GirenKodu { get; set; }
        public string MHS181_GirenSurum { get; set; }
        public string MHS181_DegistirenKaynak { get; set; }
        public Nullable<int> MHS181_DegistirenTarih { get; set; }
        public string MHS181_DegistirenSaat { get; set; }
        public string MHS181_DegistirenKodu { get; set; }
        public string MHS181_DegistirenSurum { get; set; }
        public Nullable<int> MHS181_MhsEnfYTarih { get; set; }
        public Nullable<byte> MHS181_MhsEnfYTip { get; set; }
        public Nullable<int> MHS181_MhsEnfYNo { get; set; }
        public Nullable<int> MHS181_MhsEnfYMaddeNo { get; set; }
        public Nullable<short> MHS181_MhsEnfYSiraNo { get; set; }
        public Nullable<byte> MHS181_MhsEnfYBA { get; set; }
        public Nullable<decimal> MHS181_MhsEnfYTutar { get; set; }
        public Nullable<int> MHS181_MhsEnfDTarih { get; set; }
        public Nullable<byte> MHS181_MhsEnfDTip { get; set; }
        public Nullable<int> MHS181_MhsEnfDNo { get; set; }
        public Nullable<int> MHS181_MhsEnfDMaddeNo { get; set; }
        public Nullable<short> MHS181_MhsEnfDSiraNo { get; set; }
        public Nullable<byte> MHS181_MhsEnfDBA { get; set; }
        public Nullable<decimal> MHS181_MhsEnfDTutar { get; set; }
        public string MHS181_MhsEnfAciklama { get; set; }
        public string MHS181_MhsEnfAciklama2 { get; set; }
        public Nullable<decimal> MHS181_MhsEnfAltHesapBA { get; set; }
    }
}
