//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHS204
    {
        public int MHS204_Row_ID { get; set; }
        public string MHS204_MizanHesapKodu { get; set; }
        public string MHS204_MizanHesapAdi { get; set; }
        public string MHS204_EkMizanHesapKodu { get; set; }
        public string MHS204_EkMizanHesapAdi { get; set; }
    }
}
