//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHS202
    {
        public int MHS202_Row_ID { get; set; }
        public string MHS202_TanimAdi { get; set; }
        public string MHS202_AciklamaAyrac { get; set; }
        public string MHS202_IslemKodu { get; set; }
        public Nullable<byte> MHS202_BorcAlacak { get; set; }
        public Nullable<byte> MHS202_HesapTipi { get; set; }
        public Nullable<byte> MHS202_AciklamaFlag { get; set; }
        public Nullable<byte> MHS202_AciklamaYNS { get; set; }
        public string MHS202_HesapBaslangic { get; set; }
        public string MHS202_HesapKodu { get; set; }
        public string MHS202_AciklamaAranacakDeger { get; set; }
        public Nullable<byte> MHS202_TanimTipi { get; set; }
        public string MHS202_AlanDegerleri { get; set; }
    }
}
