//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHS216
    {
        public int MHS216_Row_ID { get; set; }
        public string MHS216_FieldName { get; set; }
        public string MHS216_FieldValue { get; set; }
        public string MHS216_Phesap { get; set; }
        public Nullable<int> MHS216_PHesapTipi { get; set; }
        public Nullable<int> MHS216_PToplamTipi { get; set; }
        public Nullable<int> MHS216_Prakam { get; set; }
        public Nullable<decimal> MHS216_Poran { get; set; }
    }
}
