//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHS212
    {
        public int MHS212_Row_ID { get; set; }
        public string MHS212_GroupName { get; set; }
        public string MHS212_CalcFieldName { get; set; }
        public string MHS212_AccountName { get; set; }
        public Nullable<int> MHS212_AccountType { get; set; }
        public Nullable<int> MHS212_SumType { get; set; }
        public string MHS212_CalcFieldType { get; set; }
        public Nullable<int> MHS212_ConditionType { get; set; }
        public string MHS212_BeginValue { get; set; }
        public string MHS212_EndValue { get; set; }
        public string MHS212_GUName { get; set; }
        public Nullable<byte> MHS212_PublicDef { get; set; }
    }
}
