//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHS218
    {
        public int MHS218_Row_ID { get; set; }
        public Nullable<decimal> MHS218_OperNo { get; set; }
        public Nullable<decimal> MHS218_RowKey { get; set; }
        public Nullable<byte> MHS218_ActivePassive { get; set; }
        public Nullable<int> MHS218_TableNumber { get; set; }
        public string MHS218_RowExplanation { get; set; }
        public Nullable<decimal> MHS218_ParentNodeKey { get; set; }
        public Nullable<int> MHS218_DefinitionKey { get; set; }
        public Nullable<decimal> MHS218_OrderKey { get; set; }
        public Nullable<int> MHS218_BeyannameCode { get; set; }
    }
}
