//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHS201
    {
        public int MHS201_Row_ID { get; set; }
        public string MHS201_Kodu { get; set; }
        public string MHS201_Unvani1 { get; set; }
        public string MHS201_Unvani2 { get; set; }
        public string MHS201_VergiDairesi { get; set; }
        public string MHS201_VergiHesapNo { get; set; }
        public Nullable<int> MHS201_Ulke { get; set; }
        public string MHS201_Adres1 { get; set; }
        public string MHS201_Adres2 { get; set; }
        public string MHS201_Adres3 { get; set; }
        public string MHS201_GirenKaynak { get; set; }
        public Nullable<int> MHS201_GirenTarih { get; set; }
        public string MHS201_GirenSaat { get; set; }
        public string MHS201_GirenKodu { get; set; }
        public string MHS201_GirenSurum { get; set; }
        public string MHS201_DegistirenKaynak { get; set; }
        public Nullable<int> MHS201_DegistirenTarih { get; set; }
        public string MHS201_DegistirenSaat { get; set; }
        public string MHS201_DegistirenKodu { get; set; }
        public string MHS201_DegistirenSurum { get; set; }
    }
}
