//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHS244
    {
        public int MHS244_Row_ID { get; set; }
        public string MHS244_AltHesapKodu { get; set; }
        public Nullable<int> MHS244_IslemTarihi { get; set; }
        public Nullable<byte> MHS244_FisTipi { get; set; }
        public Nullable<int> MHS244_FisNo { get; set; }
        public Nullable<int> MHS244_SiraNo { get; set; }
        public string MHS244_Aciklama { get; set; }
        public Nullable<byte> MHS244_BorcAlacak { get; set; }
        public Nullable<decimal> MHS244_Tutar { get; set; }
        public Nullable<int> MHS244_MaddeNo { get; set; }
        public string MHS244_FisKodu { get; set; }
        public Nullable<byte> MHS244_IsleminParaBirimi { get; set; }
        public string MHS244_GirenKaynak { get; set; }
        public Nullable<int> MHS244_GirenTarih { get; set; }
        public string MHS244_GirenSaat { get; set; }
        public string MHS244_GirenKodu { get; set; }
        public string MHS244_GirenSurum { get; set; }
        public string MHS244_DegistirenKaynak { get; set; }
        public Nullable<int> MHS244_DegistirenTarih { get; set; }
        public string MHS244_DegistirenSaat { get; set; }
        public string MHS244_DegistirenKodu { get; set; }
        public string MHS244_DegistirenSurum { get; set; }
        public string MHS244_Referans { get; set; }
        public string MHS244_Aciklama2 { get; set; }
        public string MHS244_DovizCinsi { get; set; }
        public Nullable<decimal> MHS244_DovizTutari { get; set; }
        public Nullable<decimal> MHS244_DovizKuru { get; set; }
        public string MHS244_OzelKod { get; set; }
        public string MHS244_EvrakNo { get; set; }
        public string MHS244_MasrafMerkeziKodu { get; set; }
        public Nullable<decimal> MHS244_Miktar { get; set; }
        public string MHS244_Birim { get; set; }
        public Nullable<int> MHS244_EvrakTarihi { get; set; }
        public string MHS244_CHKodu { get; set; }
        public Nullable<int> MHS244_VadeTarihi { get; set; }
        public Nullable<short> MHS244_IslemTipi { get; set; }
        public Nullable<decimal> MHS244_VadeFarkiTutari { get; set; }
        public Nullable<int> MHS244_DuzeltmeyeEsasTarih { get; set; }
        public Nullable<decimal> MHS244_KrediTutari { get; set; }
        public Nullable<decimal> MHS244_KrediFaizi { get; set; }
        public Nullable<int> MHS244_KrediFaizDonBasTarih { get; set; }
        public Nullable<int> MHS244_KrediFaizDonBitTarih { get; set; }
        public Nullable<decimal> MHS244_ReelOlmFinMaliyet { get; set; }
        public Nullable<int> MHS244_DuzAitOlduguYil { get; set; }
        public Nullable<byte> MHS244_DuzAitOlduguDonem { get; set; }
        public Nullable<int> MHS244_DuzAitOlduguEvrak { get; set; }
        public Nullable<int> MHS244_DuzAitOlduguTarih { get; set; }
        public Nullable<byte> MHS244_GiderTuru { get; set; }
        public Nullable<byte> MHS244_ArindirmaSekli { get; set; }
        public Nullable<decimal> MHS244_DuzeltilmisDeger { get; set; }
        public string MHS244_BaBsFlag { get; set; }
        public string MHS244_VergiHesapNo { get; set; }
        public string MHS244_VergiDairesi { get; set; }
        public Nullable<int> MHS244_Ulke { get; set; }
        public Nullable<int> MHS244_EvrakSayisi { get; set; }
        public string MHS244_KartUnvani { get; set; }
        public Nullable<decimal> MHS244_KDVOrani { get; set; }
        public Nullable<int> MHS244_FormBYil { get; set; }
        public Nullable<short> MHS244_FormBAy { get; set; }
        public string MHS244_KartDovizCinsi { get; set; }
        public Nullable<decimal> MHS244_KartDovizTutari { get; set; }
        public Nullable<short> MHS244_EvrakTipi { get; set; }
        public Nullable<decimal> MHS244_KDVMatrahi { get; set; }
        public Nullable<decimal> MHS244_KDVTutari { get; set; }
        public Nullable<int> MHS244_SEQNo { get; set; }
        public string MHS244_IthalatNo { get; set; }
        public Nullable<int> MHS244_YevmiyeSiraNo { get; set; }
        public string MHS244_OdemeTipi { get; set; }
        public Nullable<byte> MHS244_YevmiyeEvrakTip { get; set; }
        public string MHS244_EvrakTipAciklama { get; set; }
        public Nullable<int> MHS244_KDVTevkIslemTuru { get; set; }
        public string MHS244_KDVTevkOrani { get; set; }
        public Nullable<decimal> MHS244_KDVTevkIslemBedeli { get; set; }
        public string MHS244_KaynakEvrakNo { get; set; }
        public Nullable<int> MHS244_KaynakEvrakTarihi { get; set; }
    }
}
