//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHS214
    {
        public int MHS214_Row_ID { get; set; }
        public string MHS214_FieldName { get; set; }
        public string MHS214_FieldValue { get; set; }
        public string MHS214_Phesap { get; set; }
        public Nullable<int> MHS214_PHesapTipi { get; set; }
        public Nullable<int> MHS214_PToplamTipi { get; set; }
        public Nullable<int> MHS214_Prakam { get; set; }
        public Nullable<decimal> MHS214_Poran { get; set; }
        public Nullable<decimal> MHS214_SatirNo { get; set; }
    }
}
