//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHS213
    {
        public int MHS213_Row_ID { get; set; }
        public string MHS213_FieldName { get; set; }
        public string MHS213_FieldValue { get; set; }
        public string MHS213_Phesap { get; set; }
        public Nullable<int> MHS213_PHesapTipi { get; set; }
        public Nullable<int> MHS213_PToplamTipi { get; set; }
        public Nullable<int> MHS213_Prakam { get; set; }
        public Nullable<decimal> MHS213_Poran { get; set; }
        public Nullable<byte> MHS213_KDVBeyanTipi { get; set; }
    }
}
