//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LOGEntities : DbContext
    {
        public LOGEntities()
            : base("name=LOGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppLog> AppLogs { get; set; }
        public virtual DbSet<ELMAH_Error> ELMAH_Error { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<LoginLog> LoginLogs { get; set; }
        public virtual DbSet<TumSiparisOnayLog> TumSiparisOnayLogs { get; set; }
        public virtual DbSet<DB_Aylik_SatisAnalizi> DB_Aylik_SatisAnalizi { get; set; }
        public virtual DbSet<DB_Aylik_SatisAnalizi_Tip_Kod_Doviz> DB_Aylik_SatisAnalizi_Tip_Kod_Doviz { get; set; }
        public virtual DbSet<DB_BakiyeRiskAnalizi> DB_BakiyeRiskAnalizi { get; set; }
        public virtual DbSet<DB_BekleyenSiparis_UrunGrubu_Fiyat> DB_BekleyenSiparis_UrunGrubu_Fiyat { get; set; }
        public virtual DbSet<DB_BekleyenSiparis_UrunGrubu_Miktar> DB_BekleyenSiparis_UrunGrubu_Miktar { get; set; }
        public virtual DbSet<DB_GunlukSatisAnaliziYearToDay> DB_GunlukSatisAnaliziYearToDay { get; set; }
        public virtual DbSet<DB_LokasyonBazli_SatisAnalizi> DB_LokasyonBazli_SatisAnalizi { get; set; }
        public virtual DbSet<DB_LokasyonBazli_SatisAnalizi_Kriter> DB_LokasyonBazli_SatisAnalizi_Kriter { get; set; }
        public virtual DbSet<DB_SatisBaglanti_UrunGrubu> DB_SatisBaglanti_UrunGrubu { get; set; }
        public virtual DbSet<DB_UrunGrubu_SatisAnalizi> DB_UrunGrubu_SatisAnalizi { get; set; }
        public virtual DbSet<DB_UrunGrubu_SatisAnalizi_Kriter> DB_UrunGrubu_SatisAnalizi_Kriter { get; set; }
    }
}
