//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FINSATEntities : DbContext
    {
        public FINSATEntities()
            : base("name=FINSATEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHK> CHKs { get; set; }
        public virtual DbSet<FTD> FTDs { get; set; }
        public virtual DbSet<MFK> MFKs { get; set; }
        public virtual DbSet<SPI> SPIs { get; set; }
        public virtual DbSet<STI> STIs { get; set; }
        public virtual DbSet<STK> STKs { get; set; }
    }
}
