//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Olcu
    {
        public int ID { get; set; }
        public string MalKodu { get; set; }
        public byte Tip { get; set; }
        public Nullable<decimal> En { get; set; }
        public Nullable<decimal> Boy { get; set; }
        public Nullable<decimal> Genislik { get; set; }
        public Nullable<decimal> AgirlikNet { get; set; }
        public Nullable<decimal> AgirlikBrut { get; set; }
        public Nullable<decimal> HacimNet { get; set; }
        public Nullable<decimal> HacimBrut { get; set; }
    }
}
