//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Perm()
        {
            this.RolePerms = new HashSet<RolePerm>();
        }
    
        public int ID { get; set; }
        public string PermName { get; set; }
        public bool Active { get; set; }
        public short Type { get; set; }
        public short AppType { get; set; }
        public string Group { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolePerm> RolePerms { get; set; }
    }
}
