//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Raf()
        {
            this.Bolums = new HashSet<Bolum>();
        }
    
        public int ID { get; set; }
        public int KoridorID { get; set; }
        public string RafAd { get; set; }
        public int SiraNo { get; set; }
        public bool Aktif { get; set; }
        public int Kaydeden { get; set; }
        public int KayitTarih { get; set; }
        public int Degistiren { get; set; }
        public int DegisTarih { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bolum> Bolums { get; set; }
        public virtual Koridor Koridor { get; set; }
    }
}
