//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePerm
    {
        public int ID { get; set; }
        public string RoleName { get; set; }
        public string PermName { get; set; }
        public bool Reading { get; set; }
        public bool Writing { get; set; }
        public bool Updating { get; set; }
        public bool Deleting { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string RecordUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
    
        public virtual Perm Perm { get; set; }
        public virtual Role Role { get; set; }
    }
}
