//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCS005
    {
        public int SCS005_Row_ID { get; set; }
        public string SCS005_CekNo { get; set; }
        public Nullable<int> SCS005_VadeTarihi { get; set; }
        public Nullable<decimal> SCS005_Tutar { get; set; }
        public string SCS005_CHKoduBanka { get; set; }
        public string SCS005_Banka { get; set; }
        public string SCS005_Sube { get; set; }
        public string SCS005_BankaHesapNo { get; set; }
        public string SCS005_BankaCekNo { get; set; }
        public Nullable<int> SCS005_BankaKodu { get; set; }
        public Nullable<int> SCS005_SubeKodu { get; set; }
        public string SCS005_Aciklama { get; set; }
        public string SCS005_Kod1 { get; set; }
        public string SCS005_Sehir { get; set; }
        public string SCS005_Bos { get; set; }
        public string SCS005_KarsiEvrak { get; set; }
        public Nullable<byte> SCS005_CH1 { get; set; }
        public Nullable<byte> SCS005_CH2 { get; set; }
        public Nullable<byte> SCS005_CH3 { get; set; }
        public Nullable<byte> SCS005_CH4 { get; set; }
        public Nullable<byte> SCS005_CH5 { get; set; }
        public Nullable<short> SCS005_BankaCekNoPozisyon1 { get; set; }
        public Nullable<short> SCS005_BankaCekNoPozisyon2 { get; set; }
        public Nullable<short> SCS005_BankaCekNoPozisyon3 { get; set; }
        public Nullable<short> SCS005_BankaCekNoPozisyon4 { get; set; }
        public Nullable<short> SCS005_BankaCekNoPozisyon5 { get; set; }
        public Nullable<int> SCS005_BankaCekNoPTarih1 { get; set; }
        public Nullable<int> SCS005_BankaCekNoPTarih2 { get; set; }
        public Nullable<int> SCS005_BankaCekNoPTarih3 { get; set; }
        public Nullable<int> SCS005_BankaCekNoPTarih4 { get; set; }
        public Nullable<int> SCS005_BankaCekNoPTarih5 { get; set; }
        public Nullable<byte> SCS005_EB1 { get; set; }
        public Nullable<byte> SCS005_EB2 { get; set; }
        public Nullable<byte> SCS005_EB3 { get; set; }
        public Nullable<byte> SCS005_EB4 { get; set; }
        public Nullable<byte> SCS005_EB5 { get; set; }
        public string SCS005_BordroNo1 { get; set; }
        public string SCS005_BordroNo2 { get; set; }
        public string SCS005_BordroNo3 { get; set; }
        public string SCS005_BordroNo4 { get; set; }
        public string SCS005_BordroNo5 { get; set; }
        public Nullable<short> SCS005_SonPozisyonTipi { get; set; }
        public string SCS005_HesapKodu { get; set; }
        public string SCS005_SonBordroNo { get; set; }
        public Nullable<int> SCS005_YevMaddeNo1 { get; set; }
        public Nullable<int> SCS005_YevMaddeNo2 { get; set; }
        public Nullable<int> SCS005_YevMaddeNo3 { get; set; }
        public Nullable<int> SCS005_YevMaddeNo4 { get; set; }
        public Nullable<int> SCS005_YevMaddeNo5 { get; set; }
        public Nullable<int> SCS005_YevMaddeNo6 { get; set; }
        public Nullable<int> SCS005_YevMaddeNo7 { get; set; }
        public Nullable<int> SCS005_YevMaddeNo8 { get; set; }
        public Nullable<int> SCS005_YevMaddeNo9 { get; set; }
        public Nullable<int> SCS005_YevTarihi1 { get; set; }
        public Nullable<int> SCS005_YevTarihi2 { get; set; }
        public Nullable<int> SCS005_YevTarihi3 { get; set; }
        public Nullable<int> SCS005_YevTarihi4 { get; set; }
        public Nullable<int> SCS005_YevTarihi5 { get; set; }
        public Nullable<int> SCS005_YevTarihi6 { get; set; }
        public Nullable<int> SCS005_YevTarihi7 { get; set; }
        public Nullable<int> SCS005_YevTarihi8 { get; set; }
        public Nullable<int> SCS005_YevTarihi9 { get; set; }
        public Nullable<int> SCS005_DefterKayitNo1 { get; set; }
        public Nullable<int> SCS005_DefterKayitNo2 { get; set; }
        public Nullable<int> SCS005_DefterKayitNo3 { get; set; }
        public Nullable<int> SCS005_DefterKayitNo4 { get; set; }
        public Nullable<int> SCS005_DefterKayitNo5 { get; set; }
        public Nullable<int> SCS005_DefterKayitNo6 { get; set; }
        public Nullable<int> SCS005_DefterKayitNo7 { get; set; }
        public Nullable<int> SCS005_DefterKayitNo8 { get; set; }
        public Nullable<int> SCS005_DefterKayitNo9 { get; set; }
        public Nullable<int> SCS005_IptalTarihi1 { get; set; }
        public Nullable<int> SCS005_IptalTarihi2 { get; set; }
        public Nullable<int> SCS005_IptalTarihi3 { get; set; }
        public Nullable<int> SCS005_IptalTarihi4 { get; set; }
        public Nullable<int> SCS005_IptalTarihi5 { get; set; }
        public Nullable<byte> SCS005_KayitTuru1 { get; set; }
        public Nullable<byte> SCS005_KayitTuru2 { get; set; }
        public Nullable<byte> SCS005_KayitTuru3 { get; set; }
        public Nullable<byte> SCS005_KayitTuru4 { get; set; }
        public Nullable<byte> SCS005_KayitTuru5 { get; set; }
        public Nullable<int> SCS005_KartIptalTarihi { get; set; }
        public Nullable<byte> SCS005_KartKayitTuru { get; set; }
        public Nullable<decimal> SCS005_PozisyonTutar1 { get; set; }
        public Nullable<decimal> SCS005_PozisyonTutar2 { get; set; }
        public Nullable<decimal> SCS005_PozisyonTutar3 { get; set; }
        public Nullable<decimal> SCS005_PozisyonTutar4 { get; set; }
        public Nullable<decimal> SCS005_PozisyonTutar5 { get; set; }
        public string SCS005_KaydiGirenKaynak { get; set; }
        public Nullable<int> SCS005_KaydiGirenTarih { get; set; }
        public string SCS005_KaydiGirenSaat { get; set; }
        public string SCS005_KaydiGirenKullaniciKodu { get; set; }
        public string SCS005_KaydiGirenVersiyon { get; set; }
        public string SCS005_SonDegistirenKaynak { get; set; }
        public Nullable<int> SCS005_SonDegistirenTarih { get; set; }
        public string SCS005_SonDegistirenSaat { get; set; }
        public string SCS005_SonDegistirenKullaniciKodu { get; set; }
        public string SCS005_SonDegistirenVersiyon { get; set; }
        public string SCS005_Kod2 { get; set; }
        public string SCS005_Kod3 { get; set; }
        public string SCS005_Kod4 { get; set; }
        public string SCS005_Kod5 { get; set; }
        public string SCS005_Kod6 { get; set; }
        public string SCS005_Kod7 { get; set; }
        public string SCS005_Kod8 { get; set; }
        public string SCS005_Kod9 { get; set; }
        public string SCS005_Kod10 { get; set; }
        public Nullable<decimal> SCS005_Kod11 { get; set; }
        public Nullable<decimal> SCS005_Kod12 { get; set; }
        public string SCS005_DovizCinsi { get; set; }
        public Nullable<decimal> SCS005_DovizKuru1 { get; set; }
        public Nullable<decimal> SCS005_DovizKuru2 { get; set; }
        public Nullable<decimal> SCS005_DovizKuru3 { get; set; }
        public Nullable<decimal> SCS005_DovizKuru4 { get; set; }
        public Nullable<decimal> SCS005_DovizKuru5 { get; set; }
        public Nullable<decimal> SCS005_DovizTutari1 { get; set; }
        public Nullable<decimal> SCS005_DovizTutari2 { get; set; }
        public Nullable<decimal> SCS005_DovizTutari3 { get; set; }
        public Nullable<decimal> SCS005_DovizTutari4 { get; set; }
        public Nullable<decimal> SCS005_DovizTutari5 { get; set; }
        public Nullable<byte> SCS005_CekTipi { get; set; }
        public string SCS005_IBAN { get; set; }
        public Nullable<decimal> SCS005_DovizYerelTutari1 { get; set; }
        public Nullable<decimal> SCS005_DovizYerelTutari2 { get; set; }
        public Nullable<decimal> SCS005_DovizYerelTutari3 { get; set; }
        public Nullable<decimal> SCS005_DovizYerelTutari4 { get; set; }
        public Nullable<decimal> SCS005_DovizYerelTutari5 { get; set; }
    }
}
