//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCS051
    {
        public int SCS051_Row_ID { get; set; }
        public string SCS051_GUName { get; set; }
        public Nullable<short> SCS051_SCSSenetAlSInd { get; set; }
        public Nullable<short> SCS051_SCSSenetAlGirisBordroSInd { get; set; }
        public Nullable<short> SCS051_SCSSenetAlCikisBordroSInd { get; set; }
        public Nullable<short> SCS051_SCSCekAlSInd { get; set; }
        public Nullable<short> SCS051_SCSCekAlGirisBordroSInd { get; set; }
        public Nullable<short> SCS051_SCSCekAlCikisBordroSInd { get; set; }
        public Nullable<short> SCS051_SCSSenetBrcSInd { get; set; }
        public Nullable<short> SCS051_SCSSenetBrcGirisBordroSInd { get; set; }
        public Nullable<short> SCS051_SCSSenetBrcCikisBordroSInd { get; set; }
        public Nullable<short> SCS051_SCSCekBrcSInd { get; set; }
        public Nullable<short> SCS051_SCSCekBrcGirisBordroSInd { get; set; }
        public Nullable<short> SCS051_SCSCekBrcCikisBordroSInd { get; set; }
    }
}
