//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STK005
    {
        public int STK005_Row_ID { get; set; }
        public string STK005_MalKodu { get; set; }
        public Nullable<int> STK005_IslemTarihi { get; set; }
        public Nullable<byte> STK005_GC { get; set; }
        public string STK005_CariHesapKodu { get; set; }
        public string STK005_EvrakSeriNo { get; set; }
        public Nullable<decimal> STK005_Miktari { get; set; }
        public Nullable<decimal> STK005_BirimFiyati { get; set; }
        public Nullable<decimal> STK005_Tutari { get; set; }
        public Nullable<decimal> STK005_Iskonto { get; set; }
        public Nullable<decimal> STK005_KDVTutari { get; set; }
        public Nullable<short> STK005_IslemTipi { get; set; }
        public string STK005_Kod1 { get; set; }
        public string STK005_Kod2 { get; set; }
        public string STK005_IrsaliyeNo { get; set; }
        public Nullable<byte> STK005_FaturaDurumu { get; set; }
        public Nullable<byte> STK005_MuhasebelesmeDurumu { get; set; }
        public Nullable<byte> STK005_KDVDurumu { get; set; }
        public Nullable<byte> STK005_ParaBirimi { get; set; }
        public Nullable<int> STK005_SEQNo { get; set; }
        public string STK005_GirenKaynak { get; set; }
        public Nullable<int> STK005_GirenTarih { get; set; }
        public string STK005_GirenSaat { get; set; }
        public string STK005_GirenKodu { get; set; }
        public string STK005_GirenSurum { get; set; }
        public string STK005_DegistirenKaynak { get; set; }
        public Nullable<int> STK005_DegistirenTarih { get; set; }
        public string STK005_DegistirenSaat { get; set; }
        public string STK005_DegistirenKodu { get; set; }
        public string STK005_DegistirenSurum { get; set; }
        public Nullable<byte> STK005_IptalDurumu { get; set; }
        public Nullable<int> STK005_AsilEvrakTarihi { get; set; }
        public Nullable<int> STK005_SevkTarihi { get; set; }
        public Nullable<byte> STK005_OTVDahilHaric { get; set; }
        public Nullable<decimal> STK005_OTV { get; set; }
        public Nullable<decimal> STK005_Miktar2 { get; set; }
        public Nullable<decimal> STK005_Tutar2 { get; set; }
        public Nullable<decimal> STK005_KalemIskontoOrani1 { get; set; }
        public Nullable<decimal> STK005_KalemIskontoOrani2 { get; set; }
        public Nullable<decimal> STK005_KalemIskontoOrani3 { get; set; }
        public Nullable<decimal> STK005_KalemIskontoOrani4 { get; set; }
        public Nullable<decimal> STK005_KalemIskontoOrani5 { get; set; }
        public Nullable<decimal> STK005_KalemIskontoTutari1 { get; set; }
        public Nullable<decimal> STK005_KalemIskontoTutari2 { get; set; }
        public Nullable<decimal> STK005_KalemIskontoTutari3 { get; set; }
        public Nullable<decimal> STK005_KalemIskontoTutari4 { get; set; }
        public Nullable<decimal> STK005_KalemIskontoTutari5 { get; set; }
        public string STK005_DovizCinsi { get; set; }
        public Nullable<decimal> STK005_DovizTutari { get; set; }
        public Nullable<decimal> STK005_DovizKuru { get; set; }
        public string STK005_Aciklama1 { get; set; }
        public string STK005_Aciklama2 { get; set; }
        public string STK005_Depo { get; set; }
        public string STK005_Kod3 { get; set; }
        public string STK005_Kod4 { get; set; }
        public string STK005_Kod5 { get; set; }
        public string STK005_Kod6 { get; set; }
        public string STK005_Kod7 { get; set; }
        public string STK005_Kod8 { get; set; }
        public string STK005_Kod9 { get; set; }
        public string STK005_Kod10 { get; set; }
        public Nullable<decimal> STK005_Kod11 { get; set; }
        public Nullable<decimal> STK005_Kod12 { get; set; }
        public string STK005_Vasita { get; set; }
        public string STK005_MalSeriNo { get; set; }
        public string STK005_EvrakSeriNo2 { get; set; }
        public string STK005_SiparisNo { get; set; }
        public Nullable<int> STK005_VadeTarihi { get; set; }
        public Nullable<int> STK005_IrsaliyeFaturaTarihi { get; set; }
        public Nullable<int> STK005_Tarih2 { get; set; }
        public Nullable<int> STK005_SiparisTarihi { get; set; }
        public string STK005_IadeFaturaNo { get; set; }
        public Nullable<int> STK005_IadeFaturaTarihi { get; set; }
        public Nullable<decimal> STK005_Masraf { get; set; }
        public Nullable<short> STK005_MaliyetSekli { get; set; }
        public Nullable<decimal> STK005_MaliyetTutari { get; set; }
        public Nullable<int> STK005_MaliyetTarihi { get; set; }
        public Nullable<short> STK005_MaliyetMuhasebelesmeSekli { get; set; }
        public Nullable<byte> STK005_MaliyetMuhasebelesmeDurumu { get; set; }
        public string STK005_MasrafMerkezi { get; set; }
        public Nullable<int> STK005_MuhasebeFisTarihi { get; set; }
        public Nullable<byte> STK005_MuhasebeFisTipi { get; set; }
        public Nullable<int> STK005_MuhasebeFisNo { get; set; }
        public string STK005_MuhasebeFisKodu { get; set; }
        public Nullable<short> STK005_MuhasebeSiraNo { get; set; }
        public string STK005_MuhasebeHesapNo { get; set; }
        public string STK005_MuhasebeKarsiHesapNo { get; set; }
        public Nullable<byte> STK005_MuhasebeYevmiyeSekli { get; set; }
        public Nullable<byte> STK005_Kod9Flag { get; set; }
        public Nullable<byte> STK005_Kod10Flag { get; set; }
        public Nullable<decimal> STK005_StokTrFinansmanGider { get; set; }
        public Nullable<decimal> STK005_StokTrVadeFarki { get; set; }
        public Nullable<int> STK005_StokTrKrediVadeTarihi { get; set; }
        public Nullable<decimal> STK005_StokTrSozFaizOrani { get; set; }
        public string STK005_StokTrStokDuzHesapKodu { get; set; }
        public string STK005_StokTrSmmDuzHesapKodu { get; set; }
        public Nullable<decimal> STK005_StokTrNonReelFinansGidSpk { get; set; }
        public Nullable<decimal> STK005_StokTrNonReelFinansGidMly { get; set; }
        public Nullable<decimal> STK005_StokTrDuzKatsayiSpk { get; set; }
        public Nullable<decimal> STK005_StokTrDuzKatsayiMly { get; set; }
        public Nullable<decimal> STK005_StokTrDuzTutarSpk { get; set; }
        public Nullable<decimal> STK005_StokTrDuzTutarMly { get; set; }
        public Nullable<byte> STK005_StokTrDonem { get; set; }
        public Nullable<int> STK005_StokTrYil { get; set; }
        public Nullable<decimal> STK005_StokTrDuzSatSpk { get; set; }
        public Nullable<decimal> STK005_StokTrDuzSatMly { get; set; }
        public Nullable<short> STK005_StokTrSatMalYontemi { get; set; }
        public Nullable<decimal> STK005_StokTrSatMaliyeti { get; set; }
        public Nullable<int> STK005_StokTrKrediAlimTarihi { get; set; }
        public Nullable<byte> STK005_StokTrDuzMhsFlag { get; set; }
        public Nullable<byte> STK005_StokTrSatMhsFlag { get; set; }
        public Nullable<decimal> STK005_StokTrKrediTutari { get; set; }
        public Nullable<byte> STK005_StokTrKrediArindirmaSekli { get; set; }
        public Nullable<byte> STK005_StokTrGiderTipi { get; set; }
        public string STK005_StokTrIlgiliEvrak { get; set; }
        public Nullable<int> STK005_StokTrIlgiliTarih { get; set; }
        public Nullable<byte> STK005_KDVOranFlag { get; set; }
        public Nullable<short> STK005_EvrakTipi { get; set; }
        public string STK005_TeslimCHKodu { get; set; }
        public string STK005_KarsiMuhasebeKodu { get; set; }
        public Nullable<decimal> STK005_ExtFldTutar1 { get; set; }
        public Nullable<decimal> STK005_FaturalasanMiktar { get; set; }
        public Nullable<int> STK005_KDVTevkIslemTuru { get; set; }
        public string STK005_KDVTevkOrani { get; set; }
        public Nullable<decimal> STK005_KDVTevkTutar { get; set; }
        public string STK005_IthalatNo { get; set; }
        public Nullable<byte> STK005_IthalatAktarmaFlag { get; set; }
        public string STK005_BarkodNo { get; set; }
        public Nullable<int> STK005_KarekodTarih { get; set; }
        public string STK005_PartiNo { get; set; }
        public Nullable<byte> STK005_EFaturaTipi { get; set; }
        public Nullable<short> STK005_EFaturaDurumu { get; set; }
        public string STK005_EFaturaOTVListeNo { get; set; }
        public Nullable<decimal> STK005_ToplamKalemIskontosu { get; set; }
        public string STK005_KDVMuafAciklama { get; set; }
        public string STK005_KarsiMalKodu { get; set; }
        public string STK005_UreticiMalKodu { get; set; }
        public Nullable<decimal> STK005_StopajOrani { get; set; }
        public Nullable<decimal> STK005_StopajTutari { get; set; }
        public Nullable<decimal> STK005_IthalatBedeli { get; set; }
        public string STK005_IskontoNedeni { get; set; }
        public string STK005_Birim { get; set; }
        public Nullable<decimal> STK005_FaturaMiktari { get; set; }
        public Nullable<byte> STK005_OTVTevkYokVarFlag { get; set; }
        public Nullable<decimal> STK005_OTVTevkTutar { get; set; }
        public Nullable<decimal> STK005_DovizBirimFiyati { get; set; }
        public Nullable<decimal> STK005_KDVMuafTutari { get; set; }
        public string STK005_IhracatNo { get; set; }
        public Nullable<byte> STK005_EArsivFaturaTipi { get; set; }
        public Nullable<byte> STK005_EArsivFaturaTeslimSekli { get; set; }
        public Nullable<short> STK005_EArsivFaturaDurumu { get; set; }
        public string STK005_Not1 { get; set; }
        public string STK005_Not2 { get; set; }
        public string STK005_Not3 { get; set; }
        public string STK005_Not4 { get; set; }
        public string STK005_Not5 { get; set; }
        public string STK005_AgirlikBirimi { get; set; }
        public Nullable<decimal> STK005_AgirlikBrut { get; set; }
        public Nullable<decimal> STK005_AgirlikNet { get; set; }
        public Nullable<decimal> STK005_AgirlikDara { get; set; }
        public string STK005_HacimBirimi { get; set; }
        public Nullable<decimal> STK005_HacimBrut { get; set; }
        public Nullable<decimal> STK005_HacimNet { get; set; }
        public string STK005_KapTipi { get; set; }
        public Nullable<decimal> STK005_KapAdedi { get; set; }
        public Nullable<int> STK005_FiiliIhracatTarihi { get; set; }
        public string STK005_RafKodu { get; set; }
    }
}
