//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STK003
    {
        public int STK003_Row_ID { get; set; }
        public string STK003_MamulMalKodu { get; set; }
        public string STK003_HammaddeMalKodu { get; set; }
        public Nullable<decimal> STK003_KullanilanMiktar { get; set; }
        public Nullable<decimal> STK003_HammaddeFireOrani { get; set; }
        public string STK003_HareketKodu1 { get; set; }
        public string STK003_HareketKodu2 { get; set; }
        public string STK003_KaydiGirenKaynak { get; set; }
        public Nullable<int> STK003_KaydiGirenTarih { get; set; }
        public string STK003_KaydiGirenSaat { get; set; }
        public string STK003_KaydiGirenKullaniciKodu { get; set; }
        public string STK003_KaydiGirenVersiyon { get; set; }
        public string STK003_SonDegistirenKaynak { get; set; }
        public Nullable<int> STK003_SonDegistirenTarih { get; set; }
        public string STK003_SonDegistirenSaat { get; set; }
        public string STK003_SonDegistirenKullaniciKodu { get; set; }
        public string STK003_SonDegistirenVersiyon { get; set; }
        public string STK003_DalKodu { get; set; }
        public Nullable<byte> STK003_AlternatifVarFlag { get; set; }
        public Nullable<byte> STK003_IliskiDaliFlag { get; set; }
        public Nullable<decimal> STK003_SabitFireMiktari { get; set; }
        public string STK003_HareketKodu3 { get; set; }
        public string STK003_HareketKodu4 { get; set; }
        public string STK003_HareketKodu5 { get; set; }
        public string STK003_HareketKodu6 { get; set; }
        public string STK003_HareketKodu7 { get; set; }
        public string STK003_HareketKodu8 { get; set; }
        public string STK003_HareketKodu9 { get; set; }
        public string STK003_HareketKodu10 { get; set; }
        public Nullable<decimal> STK003_HareketKodu11 { get; set; }
        public Nullable<decimal> STK003_HareketKodu12 { get; set; }
        public Nullable<byte> STK003_ToplamFlag { get; set; }
        public Nullable<byte> STK003_KullanimFlag { get; set; }
        public Nullable<byte> STK003_MaliyetTipi { get; set; }
    }
}
