//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STK007
    {
        public int STK007_Row_ID { get; set; }
        public Nullable<int> STK007_FiyatListeNo { get; set; }
        public string STK007_FiyatListeKodu { get; set; }
        public string STK007_FiyatListeAdi { get; set; }
        public string STK007_MalKodu { get; set; }
        public Nullable<int> STK007_BasDate { get; set; }
        public Nullable<int> STK007_BitDate { get; set; }
        public Nullable<short> STK007_ListeTuru { get; set; }
        public Nullable<short> STK007_CHKodTipi { get; set; }
        public string STK007_CHKod { get; set; }
        public Nullable<decimal> STK007_SatisFiyat1 { get; set; }
        public Nullable<byte> STK007_SatisKDVFlag1 { get; set; }
        public Nullable<byte> STK007_SatisBirimi1 { get; set; }
        public Nullable<decimal> STK007_SatisFiyat2 { get; set; }
        public Nullable<byte> STK007_SatisKDVFlag2 { get; set; }
        public Nullable<byte> STK007_SatisBirimi2 { get; set; }
        public Nullable<decimal> STK007_SatisFiyat3 { get; set; }
        public Nullable<byte> STK007_SatisKDVFlag3 { get; set; }
        public Nullable<byte> STK007_SatisBirimi3 { get; set; }
        public Nullable<decimal> STK007_SatisFiyat4 { get; set; }
        public Nullable<byte> STK007_SatisKDVFlag4 { get; set; }
        public Nullable<byte> STK007_SatisBirimi4 { get; set; }
        public Nullable<decimal> STK007_SatisFiyat5 { get; set; }
        public Nullable<byte> STK007_SatisKDVFlag5 { get; set; }
        public Nullable<byte> STK007_SatisBirimi5 { get; set; }
        public Nullable<decimal> STK007_AlisFiyat1 { get; set; }
        public Nullable<byte> STK007_AlisKDVFlag1 { get; set; }
        public Nullable<byte> STK007_AlisBirimi1 { get; set; }
        public Nullable<decimal> STK007_AlisFiyat2 { get; set; }
        public Nullable<byte> STK007_AlisKDVFlag2 { get; set; }
        public Nullable<byte> STK007_AlisBirimi2 { get; set; }
        public Nullable<decimal> STK007_AlisFiyat3 { get; set; }
        public Nullable<byte> STK007_AlisKDVFlag3 { get; set; }
        public Nullable<byte> STK007_AlisBirimi3 { get; set; }
        public Nullable<decimal> STK007_AlisFiyat4 { get; set; }
        public Nullable<byte> STK007_AlisKDVFlag4 { get; set; }
        public Nullable<byte> STK007_AlisBirimi4 { get; set; }
        public Nullable<decimal> STK007_AlisFiyat5 { get; set; }
        public Nullable<byte> STK007_AlisKDVFlag5 { get; set; }
        public Nullable<byte> STK007_AlisBirimi5 { get; set; }
        public string STK007_GirKaynakNo { get; set; }
        public Nullable<int> STK007_GirDate { get; set; }
        public Nullable<int> STK007_GirTime { get; set; }
        public string STK007_GirKodu { get; set; }
        public string STK007_GirVers { get; set; }
        public string STK007_DegKaynakNo { get; set; }
        public Nullable<int> STK007_DegDate { get; set; }
        public string STK007_DegTime { get; set; }
        public string STK007_DegKodu { get; set; }
        public string STK007_DegVers { get; set; }
        public Nullable<decimal> STK007_SatisDoviz1 { get; set; }
        public string STK007_SatisDovizCinsi1 { get; set; }
        public Nullable<decimal> STK007_SatisDoviz2 { get; set; }
        public string STK007_SatisDovizCinsi2 { get; set; }
        public Nullable<decimal> STK007_SatisDoviz3 { get; set; }
        public string STK007_SatisDovizCinsi3 { get; set; }
        public Nullable<decimal> STK007_AlisDoviz1 { get; set; }
        public string STK007_AlisDovizCinsi1 { get; set; }
        public Nullable<decimal> STK007_AlisDoviz2 { get; set; }
        public string STK007_AlisDovizCinsi2 { get; set; }
        public Nullable<decimal> STK007_AlisDoviz3 { get; set; }
        public string STK007_AlisDovizCinsi3 { get; set; }
        public Nullable<short> STK007_ValorGun1 { get; set; }
        public Nullable<short> STK007_ValorGun2 { get; set; }
        public Nullable<short> STK007_ValorGun3 { get; set; }
        public Nullable<short> STK007_ValorGun4 { get; set; }
        public Nullable<short> STK007_ValorGun5 { get; set; }
        public Nullable<short> STK007_DvzValorGun1 { get; set; }
        public Nullable<short> STK007_DvzValorGun2 { get; set; }
        public Nullable<short> STK007_DvzValorGun3 { get; set; }
    }
}
