//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STK002
    {
        public int STK002_Row_ID { get; set; }
        public string STK002_MalKodu { get; set; }
        public Nullable<int> STK002_IslemTarihi { get; set; }
        public Nullable<byte> STK002_GC { get; set; }
        public string STK002_CariHesapKodu { get; set; }
        public string STK002_EvrakSeriNo { get; set; }
        public Nullable<decimal> STK002_Miktari { get; set; }
        public Nullable<decimal> STK002_BirimFiyati { get; set; }
        public Nullable<decimal> STK002_Tutari { get; set; }
        public Nullable<decimal> STK002_Iskonto { get; set; }
        public Nullable<decimal> STK002_KDVTutari { get; set; }
        public Nullable<short> STK002_IslemTipi { get; set; }
        public string STK002_Kod1 { get; set; }
        public string STK002_Kod2 { get; set; }
        public string STK002_IrsaliyeNo { get; set; }
        public Nullable<decimal> STK002_TeslimMiktari { get; set; }
        public Nullable<byte> STK002_SipDurumu { get; set; }
        public string STK002_Bos { get; set; }
        public Nullable<byte> STK002_KDVDurumu { get; set; }
        public Nullable<int> STK002_TeslimTarihi { get; set; }
        public Nullable<byte> STK002_ParaBirimi { get; set; }
        public Nullable<int> STK002_SEQNo { get; set; }
        public string STK002_GirenKaynak { get; set; }
        public Nullable<int> STK002_GirenTarih { get; set; }
        public string STK002_GirenSaat { get; set; }
        public string STK002_GirenKodu { get; set; }
        public string STK002_GirenSurum { get; set; }
        public string STK002_DegistirenKaynak { get; set; }
        public Nullable<int> STK002_DegistirenTarih { get; set; }
        public string STK002_DegistirenSaat { get; set; }
        public string STK002_DegistirenKodu { get; set; }
        public string STK002_DegistirenSurum { get; set; }
        public Nullable<byte> STK002_IptalDurumu { get; set; }
        public Nullable<int> STK002_AsilEvrakTarihi { get; set; }
        public Nullable<decimal> STK002_Miktar2 { get; set; }
        public Nullable<decimal> STK002_Tutar2 { get; set; }
        public Nullable<decimal> STK002_KalemIskontoOrani1 { get; set; }
        public Nullable<decimal> STK002_KalemIskontoOrani2 { get; set; }
        public Nullable<decimal> STK002_KalemIskontoOrani3 { get; set; }
        public Nullable<decimal> STK002_KalemIskontoOrani4 { get; set; }
        public Nullable<decimal> STK002_KalemIskontoOrani5 { get; set; }
        public Nullable<decimal> STK002_KalemIskontoTutari1 { get; set; }
        public Nullable<decimal> STK002_KalemIskontoTutari2 { get; set; }
        public Nullable<decimal> STK002_KalemIskontoTutari3 { get; set; }
        public Nullable<decimal> STK002_KalemIskontoTutari4 { get; set; }
        public Nullable<decimal> STK002_KalemIskontoTutari5 { get; set; }
        public string STK002_DovizCinsi { get; set; }
        public Nullable<decimal> STK002_DovizTutari { get; set; }
        public Nullable<decimal> STK002_DovizKuru { get; set; }
        public string STK002_Aciklama1 { get; set; }
        public string STK002_Aciklama2 { get; set; }
        public string STK002_Depo { get; set; }
        public string STK002_Kod3 { get; set; }
        public string STK002_Kod4 { get; set; }
        public string STK002_Kod5 { get; set; }
        public string STK002_Kod6 { get; set; }
        public string STK002_Kod7 { get; set; }
        public string STK002_Kod8 { get; set; }
        public string STK002_Kod9 { get; set; }
        public string STK002_Kod10 { get; set; }
        public Nullable<decimal> STK002_Kod11 { get; set; }
        public Nullable<decimal> STK002_Kod12 { get; set; }
        public string STK002_Vasita { get; set; }
        public string STK002_MalSeriNo { get; set; }
        public Nullable<int> STK002_VadeTarihi { get; set; }
        public Nullable<decimal> STK002_Masraf { get; set; }
        public string STK002_EvrakSeriNo2 { get; set; }
        public Nullable<int> STK002_Tarih2 { get; set; }
        public Nullable<byte> STK002_Kod9Flag { get; set; }
        public Nullable<byte> STK002_Kod10Flag { get; set; }
        public Nullable<byte> STK002_KDVOranFlag { get; set; }
        public string STK002_TeslimCHKodu { get; set; }
        public string STK002_MasrafMerkezi { get; set; }
        public Nullable<int> STK002_SonSevkTarihi { get; set; }
        public string STK002_EFaturaOTVListeNo { get; set; }
        public string STK002_KDVMuafAciklama { get; set; }
        public Nullable<decimal> STK002_DovizBirimFiyati { get; set; }
        public string STK002_Not1 { get; set; }
        public string STK002_Not2 { get; set; }
        public string STK002_Not3 { get; set; }
        public string STK002_Not4 { get; set; }
        public string STK002_Not5 { get; set; }
    }
}
