//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STK008
    {
        public int STK008_Row_ID { get; set; }
        public Nullable<short> STK008_MalKoduTipi { get; set; }
        public string STK008_MalKodu { get; set; }
        public Nullable<int> STK008_BasDate { get; set; }
        public Nullable<int> STK008_BitDate { get; set; }
        public Nullable<short> STK008_IndTuru { get; set; }
        public Nullable<short> STK008_IndCHKodTipi { get; set; }
        public string STK008_IndCHKod { get; set; }
        public Nullable<decimal> STK008_IndOrani { get; set; }
        public string STK008_GirKaynakNo { get; set; }
        public Nullable<int> STK008_GirDate { get; set; }
        public string STK008_GirTime { get; set; }
        public string STK008_GirKodu { get; set; }
        public string STK008_GirVers { get; set; }
        public string STK008_DegKaynakNo { get; set; }
        public Nullable<int> STK008_DegDate { get; set; }
        public string STK008_DegTime { get; set; }
        public string STK008_DegKodu { get; set; }
        public string STK008_DegVers { get; set; }
    }
}
