//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STK150
    {
        public int STK150_Row_ID { get; set; }
        public Nullable<byte> STK150_GC { get; set; }
        public string STK150_EvrakSeriNo { get; set; }
        public Nullable<int> STK150_IslemTarihi { get; set; }
        public string STK150_CariHesapKodu { get; set; }
        public Nullable<short> STK150_EvrakTipi { get; set; }
        public Nullable<int> STK150_SEQNo { get; set; }
        public Nullable<short> STK150_IslemTipi { get; set; }
        public string STK150_MalKodu { get; set; }
        public Nullable<decimal> STK150_Miktari { get; set; }
        public string STK150_Depo { get; set; }
        public Nullable<byte> STK150_GC2 { get; set; }
        public string STK150_EvrakSeriNo2 { get; set; }
        public Nullable<int> STK150_IslemTarihi2 { get; set; }
        public string STK150_CariHesapKodu2 { get; set; }
        public Nullable<short> STK150_EvrakTipi2 { get; set; }
        public Nullable<int> STK150_SEQNo2 { get; set; }
        public Nullable<short> STK150_IslemTipi2 { get; set; }
        public string STK150_MalKodu2 { get; set; }
        public Nullable<decimal> STK150_Miktari2 { get; set; }
        public string STK150_Depo2 { get; set; }
        public string STK150_GirenKaynak { get; set; }
        public Nullable<int> STK150_GirenTarih { get; set; }
        public string STK150_GirenSaat { get; set; }
        public string STK150_GirenKodu { get; set; }
        public string STK150_GirenSurum { get; set; }
        public string STK150_DegistirenKaynak { get; set; }
        public Nullable<int> STK150_DegistirenTarih { get; set; }
        public string STK150_DegistirenSaat { get; set; }
        public string STK150_DegistirenKodu { get; set; }
        public string STK150_DegistirenSurum { get; set; }
    }
}
