//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tahsilat
    {
        public int ID { get; set; }
        public int EvrakID { get; set; }
        public decimal OdenenTutar { get; set; }
        public string TahsilatNo { get; set; }
        public short OdemeEvrakTipi { get; set; }
        public int Tarih { get; set; }
    }
}
