//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TK_KAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TK_KAT()
        {
            this.Yerlestirmes = new HashSet<Yerlestirme>();
            this.Yerlestirme_Hareketler = new HashSet<Yerlestirme_Hareketler>();
        }
    
        public int ID { get; set; }
        public int BolumID { get; set; }
        public string Kat { get; set; }
        public decimal Boy { get; set; }
        public decimal Derinlik { get; set; }
        public decimal En { get; set; }
        public decimal AgirlikKapasite { get; set; }
        public int Ozellik { get; set; }
        public string Aciklama { get; set; }
        public int SiraNo { get; set; }
        public bool Aktif { get; set; }
        public string Kaydeden { get; set; }
        public int KayitTarih { get; set; }
        public string Degistiren { get; set; }
        public int DegisTarih { get; set; }
    
        public virtual TK_BOL TK_BOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yerlestirme> Yerlestirmes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yerlestirme_Hareketler> Yerlestirme_Hareketler { get; set; }
        public virtual ComboItemName ComboItemName { get; set; }
    }
}
