//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TK_RAF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TK_RAF()
        {
            this.TK_BOL = new HashSet<TK_BOL>();
            this.TK_KAT = new HashSet<TK_KAT>();
        }
    
        public int ID { get; set; }
        public int KoridorID { get; set; }
        public string Raf { get; set; }
        public decimal Derinlik { get; set; }
        public int SiraNo { get; set; }
        public bool Aktif { get; set; }
        public string Kaydeden { get; set; }
        public int KayitTarih { get; set; }
        public string Degistiren { get; set; }
        public int DegisTarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TK_BOL> TK_BOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TK_KAT> TK_KAT { get; set; }
        public virtual TK_KOR TK_KOR { get; set; }
    }
}
