//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public int ID { get; set; }
        public string SirketKod { get; set; }
        public int GirisDepoID { get; set; }
        public int CikisDepoID { get; set; }
        public int AraDepoID { get; set; }
        public string Malzemeler { get; set; }
        public int OlusturanID { get; set; }
        public int OlusturmaTarihi { get; set; }
        public int OlusturmaSaati { get; set; }
        public bool Onay { get; set; }
        public Nullable<int> OnaylayanID { get; set; }
        public Nullable<int> OnaylamaTarihi { get; set; }
        public Nullable<int> OnaylamaSaati { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Depo Depo { get; set; }
        public virtual Depo Depo1 { get; set; }
        public virtual Depo Depo2 { get; set; }
    }
}
