//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer_Detay
    {
        public int ID { get; set; }
        public int TransferID { get; set; }
        public string MalKodu { get; set; }
        public decimal Miktar { get; set; }
        public string Birim { get; set; }
    
        public virtual Transfer Transfer { get; set; }
    }
}
