//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transfer()
        {
            this.Transfer_Detay = new HashSet<Transfer_Detay>();
        }
    
        public int ID { get; set; }
        public int GorevID { get; set; }
        public string SirketKod { get; set; }
        public int GirisDepoID { get; set; }
        public int CikisDepoID { get; set; }
        public int AraDepoID { get; set; }
        public bool Onay { get; set; }
        public string Onaylayan { get; set; }
        public Nullable<int> OnaylamaTarihi { get; set; }
        public Nullable<int> OnaylamaSaati { get; set; }
    
        public virtual Depo Depo { get; set; }
        public virtual Depo Depo1 { get; set; }
        public virtual Depo Depo2 { get; set; }
        public virtual Gorev Gorev { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer_Detay> Transfer_Detay { get; set; }
    }
}
