//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TumSiparisOnayLog
    {
        public int ID { get; set; }
        public string HesapKodu { get; set; }
        public string Firma { get; set; }
        public string SiparisTuru { get; set; }
        public string OnayDurumu { get; set; }
        public string TipKodu { get; set; }
        public decimal KrediLimiti { get; set; }
        public decimal Bakiye { get; set; }
        public decimal SCek { get; set; }
        public decimal TCek { get; set; }
        public decimal PRTBakiye { get; set; }
        public string Kod2 { get; set; }
        public decimal Kod3OrtBakiye { get; set; }
        public decimal Kod3OrtGun { get; set; }
        public decimal OrtGun { get; set; }
        public decimal SicakSiparis { get; set; }
        public decimal SogukSiparis { get; set; }
        public decimal GunIciSiparis { get; set; }
        public string CHKAralik { get; set; }
        public decimal RiskBakiyesi { get; set; }
        public string TipKodlari { get; set; }
        public string RiskBakiyeAralik { get; set; }
        public string RiskAralik { get; set; }
        public string SirketAralik { get; set; }
        public string RoleName { get; set; }
        public string Degistiren { get; set; }
        public int DegisTarih { get; set; }
        public string Unvan { get; set; }
        public string EvrakNo { get; set; }
        public decimal Risk { get; set; }
    }
}
