//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR01
    {
        public int ID { get; set; }
        public string Sirket { get; set; }
        public short Tip { get; set; }
        public string Kod { get; set; }
        public string Sifre { get; set; }
        public string AdSoyad { get; set; }
        public string Email { get; set; }
        public string RoleName { get; set; }
        public string Tema { get; set; }
        public bool Admin { get; set; }
        public bool Aktif { get; set; }
        public string Kaydeden { get; set; }
        public int KayitTarih { get; set; }
        public int KayitSaat { get; set; }
        public short KayitKaynak { get; set; }
        public string KayitSurum { get; set; }
        public string Degistiren { get; set; }
        public int DegisTarih { get; set; }
        public int DegisSaat { get; set; }
        public short DegisKaynak { get; set; }
        public string DegisSurum { get; set; }
    }
}
