//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebMenu()
        {
            this.WebMenu1 = new HashSet<WebMenu>();
            this.Roles = new HashSet<Role>();
        }
    
        public short ID { get; set; }
        public int SiteTipiID { get; set; }
        public int MenuYeriID { get; set; }
        public string Ad { get; set; }
        public byte Sira { get; set; }
        public string Url { get; set; }
        public Nullable<short> SimgeID { get; set; }
        public Nullable<short> UstMenuID { get; set; }
        public bool Aktif { get; set; }
    
        public virtual Simge Simge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebMenu> WebMenu1 { get; set; }
        public virtual WebMenu WebMenu2 { get; set; }
        public virtual ComboItem_Name ComboItem_Name { get; set; }
        public virtual ComboItem_Name ComboItem_Name1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
    }
}
