//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yer_Log
    {
        public int ID { get; set; }
        public int KatID { get; set; }
        public string HucreAd { get; set; }
        public string MalKodu { get; set; }
        public string Birim { get; set; }
        public decimal Miktar { get; set; }
        public bool GC { get; set; }
        public string Kaydeden { get; set; }
        public int KayitTarihi { get; set; }
        public int KayitSaati { get; set; }
        public Nullable<int> IrsaliyeID { get; set; }
    
        public virtual IR IR { get; set; }
        public virtual Kat Kat { get; set; }
    }
}
