//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Mysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class hareket
    {
        public int mid { get; set; }
        public int id { get; set; }
        public decimal miktar { get; set; }
        public string musteri { get; set; }
        public System.DateTime tarih { get; set; }
    }
}
