//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Mysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class kblstok2
    {
        public int id { get; set; }
        public int sid { get; set; }
        public string marka { get; set; }
        public string cins { get; set; }
        public string kesit { get; set; }
        public Nullable<decimal> miktar { get; set; }
        public string depo { get; set; }
        public string renk { get; set; }
        public string makara { get; set; }
        public string rezerve { get; set; }
        public string tip { get; set; }
        public string satici { get; set; }
        public string musteri { get; set; }
        public Nullable<decimal> rmiktar { get; set; }
        public Nullable<System.TimeSpan> sure { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string makarano { get; set; }
    }
}
