//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Mysql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KabloEntities : DbContext
    {
        public KabloEntities()
            : base("name=KabloEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cin> cins { get; set; }
        public virtual DbSet<depo> depoes { get; set; }
        public virtual DbSet<fiyat> fiyats { get; set; }
        public virtual DbSet<index> indices { get; set; }
        public virtual DbSet<kesit> kesits { get; set; }
        public virtual DbSet<kesit_kop> kesit_kop { get; set; }
        public virtual DbSet<makara> makaras { get; set; }
        public virtual DbSet<marka> markas { get; set; }
        public virtual DbSet<renk> renks { get; set; }
        public virtual DbSet<rezerve_onay> rezerve_onay { get; set; }
        public virtual DbSet<stok> stoks { get; set; }
        public virtual DbSet<sure> sures { get; set; }
        public virtual DbSet<kblstok2> kblstok2 { get; set; }
        public virtual DbSet<hareket> harekets { get; set; }
        public virtual DbSet<kblstok> kblstoks { get; set; }
    }
}
