//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms12m.Entity.Mysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class rezerve_onay
    {
        public int id { get; set; }
        public int sid { get; set; }
        public string marka { get; set; }
        public string kesit { get; set; }
        public string cins { get; set; }
        public double rmiktar { get; set; }
        public string satici { get; set; }
        public string onay { get; set; }
        public System.DateTime tarih { get; set; }
    }
}
